server:
  port: 7777

logging:
  level:
    org:
      springframework:
        boot: INFO
    com:
      adamludzia:
        invoicing: INFO
        invoicing.db: DEBUG
        
  spring:
    profiles:
      active: sql
    flyway:
      enabled: false
    mvc:
      pathmatch:
        matching-strategy: ant_path_matcher
