server:
  port: 7777

logging:
  level:
    org:
      springframework:
        boot: INFO
    com:
      adamludzia:
        invoicing: WARN
        invoicing.db: DEBUG
        
  spring:
    profiles:
      active: memory
    flyway:
      enabled: false
